### ISSUE TITLE
[Meta-issue] Issues to make upstream acceptance easier

### ISSUE THREAD

**Issue by trown** [redhat-openstack/ansible-role-tripleo-image-build#14]
This is a meta issue to track all issues related to getting this role accepted upstream as THE way to build tripleo images.
- [ ] https://github.com/redhat-openstack/ansible-role-tripleo-image-build/issues/15
- [ ] https://github.com/redhat-openstack/ansible-role-tripleo-image-build/issues/16
- [ ] https://github.com/redhat-openstack/ansible-role-tripleo-image-build/issues/17

**Comment by halcyondude** [comment]
#17 has been merged
